<a href="https://colab.research.google.com/github/jhj1819/Machine-learning/blob/main/H2_1020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('/content/sample_data/ThoracicSurgery.csv')

In [3]:
data.head()

id   DGN  PRE4  PRE5  PRE6 PRE7 PRE8 PRE9 PRE10 PRE11 PRE14 PRE17 PRE19  \
0   1  DGN2  2.88  2.16  PRZ1    F    F    F     T     T  OC14     F     F   
1   2  DGN3  3.40  1.88  PRZ0    F    F    F     F     F  OC12     F     F   
2   3  DGN3  2.76  2.08  PRZ1    F    F    F     T     F  OC11     F     F   
3   4  DGN3  3.68  3.04  PRZ0    F    F    F     F     F  OC11     F     F   
4   5  DGN3  2.44  0.96  PRZ2    F    T    F     T     T  OC11     F     F   

  PRE25 PRE30 PRE32  AGE Risk1Yr  
0     F     T     F   60       F  
1     F     T     F   51       F  
2     F     T     F   59       F  
3     F     F     F   54       F  
4     F     T     F   73       T

In [4]:
data.shape

(470, 18)

In [5]:
data.isnull().sum()

id         0
DGN        0
PRE4       0
PRE5       0
PRE6       0
PRE7       0
PRE8       0
PRE9       0
PRE10      0
PRE11      0
PRE14      0
PRE17      0
PRE19      0
PRE25      0
PRE30      0
PRE32      0
AGE        0
Risk1Yr    0
dtype: int64

In [10]:
# id를 index 칼럼으로
data = data.set_index('id') ## or read할때 , index_col = 'id'

In [14]:
# DGN 칼럼 삭제
data = data.drop('DGN', axis = 1)

In [15]:
# X, y 분리
X = data.drop('Risk1Yr', axis=1)
y = data['Risk1Yr']

In [16]:
X.head()

PRE4  PRE5  PRE6 PRE7 PRE8 PRE9 PRE10 PRE11 PRE14 PRE17 PRE19 PRE25 PRE30  \
id                                                                              
1   2.88  2.16  PRZ1    F    F    F     T     T  OC14     F     F     F     T   
2   3.40  1.88  PRZ0    F    F    F     F     F  OC12     F     F     F     T   
3   2.76  2.08  PRZ1    F    F    F     T     F  OC11     F     F     F     T   
4   3.68  3.04  PRZ0    F    F    F     F     F  OC11     F     F     F     F   
5   2.44  0.96  PRZ2    F    T    F     T     T  OC11     F     F     F     T   

   PRE32  AGE  
id             
1      F   60  
2      F   51  
3      F   59  
4      F   54  
5      F   73

In [17]:
y.head()

id
1    F
2    F
3    F
4    F
5    T
Name: Risk1Yr, dtype: object

In [18]:
# 훈련/ 테스트 데이터 분리
from sklearn.model_selection import train_test_split

In [167]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state=1, stratify = y)

In [33]:
y_train.value_counts() / y_train.shape[0]


Risk1Yr
F    0.852273
T    0.147727
Name: count, dtype: float64

In [35]:
y_test.value_counts() / y_test.shape[0]

Risk1Yr
F    0.847458
T    0.152542
Name: count, dtype: float64

In [168]:
#훈련데이터 인코딩 F 는 0 T 는
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()
labelEncoder.fit(y_train)
labelEncoder.classes_

array(['F', 'T'], dtype=object)

In [169]:
y_test = labelEncoder.transform(y_test)
y_train = labelEncoder.transform(y_train)

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'LabelEncoder'

In [164]:
y_train = labelEncoder.transform(y_train)

In [51]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,

In [39]:
# 수동 매핑 방법
# y_train = y_train.map({'T':0, 'F':1})

TypeError: 'set' object is not callable

In [56]:
# 특성의 자료형 분석해서, 연속형 특성은 리스트 num, 범주형특성은 리스트 cat에
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 352 entries, 168 to 365
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   PRE4    352 non-null    float64
 1   PRE5    352 non-null    float64
 2   PRE6    352 non-null    object 
 3   PRE7    352 non-null    object 
 4   PRE8    352 non-null    object 
 5   PRE9    352 non-null    object 
 6   PRE10   352 non-null    object 
 7   PRE11   352 non-null    object 
 8   PRE14   352 non-null    object 
 9   PRE17   352 non-null    object 
 10  PRE19   352 non-null    object 
 11  PRE25   352 non-null    object 
 12  PRE30   352 non-null    object 
 13  PRE32   352 non-null    object 
 14  AGE     352 non-null    int64  
dtypes: float64(2), int64(1), object(12)
memory usage: 44.0+ KB


In [58]:
num = ['PRE4', 'PRE5', 'AGE']
cat = list(set(X_train.columns) - set(num))

In [59]:
X_train_num = X_train[num]

In [60]:
X_train.describe()

PRE4        PRE5         AGE
count  352.000000  352.000000  352.000000
mean     3.274915    4.635000   62.340909
std      0.866295   11.991257    8.411275
min      1.440000    1.000000   37.000000
25%      2.600000    1.960000   57.000000
50%      3.120000    2.400000   62.000000
75%      3.847500    3.005000   69.000000
max      6.300000   86.300000   87.000000

In [61]:
X_train_cat = X_train[cat]

In [65]:
for cat_name in cat:
  print(f'{cat_name}의 범주별 개수 {X_train_cat[cat_name].value_counts()}')

PRE6의 범주별 개수 PRE6
PRZ1    231
PRZ0    102
PRZ2     19
Name: count, dtype: int64
PRE11의 범주별 개수 PRE11
F    298
T     54
Name: count, dtype: int64
PRE14의 범주별 개수 PRE14
OC12    182
OC11    138
OC13     16
OC14     16
Name: count, dtype: int64
PRE8의 범주별 개수 PRE8
F    304
T     48
Name: count, dtype: int64
PRE32의 범주별 개수 PRE32
F    350
T      2
Name: count, dtype: int64
PRE19의 범주별 개수 PRE19
F    350
T      2
Name: count, dtype: int64
PRE25의 범주별 개수 PRE25
F    347
T      5
Name: count, dtype: int64
PRE30의 범주별 개수 PRE30
T    290
F     62
Name: count, dtype: int64
PRE9의 범주별 개수 PRE9
F    330
T     22
Name: count, dtype: int64
PRE7의 범주별 개수 PRE7
F    328
T     24
Name: count, dtype: int64
PRE17의 범주별 개수 PRE17
F    329
T     23
Name: count, dtype: int64
PRE10의 범주별 개수 PRE10
T    241
F    111
Name: count, dtype: int64


In [66]:
from sklearn.preprocessing import OneHotEncoder

In [71]:
one_hot_encoder = OneHotEncoder(sparse_output= False, drop = 'first', handle_unknown = 'ignore')

In [137]:
# X_train_cat_encoded = one_hot_encoder(X_train_cat) fit으로 해야지..
one_hot_encoder.fit(X_train_cat)

OneHotEncoder(drop='first', handle_unknown='ignore', sparse_output=False)

In [138]:
# 생성된 가변수의 이름
one_hot_encoder.get_feature_names_out()

array(['PRE6_PRZ1', 'PRE6_PRZ2', 'PRE11_T', 'PRE14_OC12', 'PRE14_OC13',
       'PRE14_OC14', 'PRE8_T', 'PRE32_T', 'PRE19_T', 'PRE25_T', 'PRE30_T',
       'PRE9_T', 'PRE7_T', 'PRE17_T', 'PRE10_T'], dtype=object)

In [76]:
x_train_cat_encoded = pd.DataFrame(one_hot_encoder.transform(X_train_cat),
                                   columns = one_hot_encoder.get_feature_names_out(),
                                   index = X_train_cat.index)

In [78]:
x_train_cat_encoded.head(5)

PRE6_PRZ1  PRE6_PRZ2  PRE11_T  PRE14_OC12  PRE14_OC13  PRE14_OC14  \
id                                                                       
168        1.0        0.0      1.0         0.0         0.0         0.0   
285        0.0        0.0      0.0         0.0         0.0         0.0   
223        1.0        0.0      0.0         1.0         0.0         0.0   
163        1.0        0.0      0.0         1.0         0.0         0.0   
150        0.0        0.0      0.0         0.0         0.0         0.0   

     PRE8_T  PRE32_T  PRE19_T  PRE25_T  PRE30_T  PRE9_T  PRE7_T  PRE17_T  \
id                                                                         
168     0.0      0.0      0.0      0.0      1.0     0.0     0.0      0.0   
285     0.0      0.0      0.0      0.0      1.0     0.0     0.0      0.0   
223     0.0      0.0      0.0      0.0      1.0     1.0     0.0      0.0   
163     1.0      0.0      0.0      0.0      1.0     0.0     1.0      0.0   
150     0.0      0.0      0.0      0.0      1.0     0.0     0.0      0.0   

     PRE10_T  
id            
168      1.0  
285      0.0  
223      1.0  
163      1.0  
150      0.0

In [80]:
# 연속, 카테고리 연결
X_train_encoded = pd.concat([X_train_num, x_train_cat_encoded], axis = 1)

In [81]:
## 표준화
from sklearn.preprocessing import StandardScaler

In [83]:
scaler = StandardScaler()

In [88]:
 X_train_std = scaler.fit_transform(X_train_encoded)

In [90]:
X_train_std

array([[-0.81487036, -0.24343982,  2.22150054, ..., -0.27050089,
        -0.26440275,  0.67866112],
       [-1.10386641, -0.22673726, -0.39775954, ..., -0.27050089,
        -0.26440275, -1.47348945],
       [ 1.76297446, -0.10230318, -0.99304592, ..., -0.27050089,
        -0.26440275,  0.67866112],
       ...,
       [ 1.53177762, -0.09311677, -1.23116047, ..., -0.27050089,
        -0.26440275,  0.67866112],
       [-0.54899399, -0.20001316,  0.9118705 , ...,  3.6968455 ,
        -0.26440275,  0.67866112],
       [-1.10386641, -0.24343982, -0.75493137, ..., -0.27050089,
        -0.26440275,  0.67866112]])

In [91]:

# 원핫인코딩 -> 연속, 범주 나눠야함
# 표준화...


In [92]:
X_test.info()


<class 'pandas.core.frame.DataFrame'>
Index: 118 entries, 370 to 320
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   PRE4    118 non-null    float64
 1   PRE5    118 non-null    float64
 2   PRE6    118 non-null    object 
 3   PRE7    118 non-null    object 
 4   PRE8    118 non-null    object 
 5   PRE9    118 non-null    object 
 6   PRE10   118 non-null    object 
 7   PRE11   118 non-null    object 
 8   PRE14   118 non-null    object 
 9   PRE17   118 non-null    object 
 10  PRE19   118 non-null    object 
 11  PRE25   118 non-null    object 
 12  PRE30   118 non-null    object 
 13  PRE32   118 non-null    object 
 14  AGE     118 non-null    int64  
dtypes: float64(2), int64(1), object(12)
memory usage: 14.8+ KB


In [93]:
X_test_num = ['PRE4', 'PRE5', 'AGE']

In [102]:
X_test_cat = X_test[list(set(X_test.columns) - set(X_test_num))]

In [130]:
X_test_cat

PRE6 PRE11 PRE14 PRE8 PRE32 PRE19 PRE25 PRE30 PRE9 PRE7 PRE17 PRE10
id                                                                      
370  PRZ0     F  OC12    F     F     F     F     T    F    F     F     F
236  PRZ1     F  OC12    F     F     F     F     T    F    F     F     T
467  PRZ0     F  OC11    F     F     F     F     T    F    F     F     F
216  PRZ1     F  OC12    T     F     F     F     T    F    F     F     T
237  PRZ1     T  OC12    F     F     F     F     T    F    F     F     T
..    ...   ...   ...  ...   ...   ...   ...   ...  ...  ...   ...   ...
4    PRZ0     F  OC11    F     F     F     F     F    F    F     F     F
180  PRZ2     T  OC12    F     F     F     F     T    F    F     F     T
161  PRZ0     F  OC12    F     F     F     F     F    F    F     F     F
437  PRZ1     F  OC12    F     F     F     F     T    T    F     F     T
320  PRZ0     F  OC11    F     F     F     F     T    F    F     F     F

[118 rows x 12 columns]

In [105]:
X_test_num = X_test[num]

In [97]:
# 위에서 선언했으니.. 연습삼아..
one_hot_encoder_2 = OneHotEncoder(drop = 'first', sparse_output = False, handle_unknown = 'ignore')

In [131]:
# 원핫 인코딩은 테스트데이터에 대해서.. 훈련데이터에서 쓴걸 이어서 써야하나..?
X_test_cat_encoded = one_hot_encoder.transform(X_test_cat)
X_test_cat_encoded


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:486: UserWarning: X has feature names, but OneHotEncoder was fitted without feature names
  warnings.warn(


array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [139]:
one_hot_encoder.get_feature_names_out()

array(['PRE6_PRZ1', 'PRE6_PRZ2', 'PRE11_T', 'PRE14_OC12', 'PRE14_OC13',
       'PRE14_OC14', 'PRE8_T', 'PRE32_T', 'PRE19_T', 'PRE25_T', 'PRE30_T',
       'PRE9_T', 'PRE7_T', 'PRE17_T', 'PRE10_T'], dtype=object)

In [140]:
X_test_cat_encoded = pd.DataFrame(X_test_cat_encoded,
                                  columns = one_hot_encoder.get_feature_names_out(),
                                  index = X_test_cat.index)

In [141]:
X_test_cat_encoded

PRE6_PRZ1  PRE6_PRZ2  PRE11_T  PRE14_OC12  PRE14_OC13  PRE14_OC14  \
id                                                                       
370        0.0        0.0      0.0         1.0         0.0         0.0   
236        1.0        0.0      0.0         1.0         0.0         0.0   
467        0.0        0.0      0.0         0.0         0.0         0.0   
216        1.0        0.0      0.0         1.0         0.0         0.0   
237        1.0        0.0      1.0         1.0         0.0         0.0   
..         ...        ...      ...         ...         ...         ...   
4          0.0        0.0      0.0         0.0         0.0         0.0   
180        0.0        1.0      1.0         1.0         0.0         0.0   
161        0.0        0.0      0.0         1.0         0.0         0.0   
437        1.0        0.0      0.0         1.0         0.0         0.0   
320        0.0        0.0      0.0         0.0         0.0         0.0   

     PRE8_T  PRE32_T  PRE19_T  PRE25_T  PRE30_T  PRE9_T  PRE7_T  PRE17_T  \
id                                                                         
370     0.0      0.0      0.0      0.0      1.0     0.0     0.0      0.0   
236     0.0      0.0      0.0      0.0      1.0     0.0     0.0      0.0   
467     0.0      0.0      0.0      0.0      1.0     0.0     0.0      0.0   
216     1.0      0.0      0.0      0.0      1.0     0.0     0.0      0.0   
237     0.0      0.0      0.0      0.0      1.0     0.0     0.0      0.0   
..      ...      ...      ...      ...      ...     ...     ...      ...   
4       0.0      0.0      0.0      0.0      0.0     0.0     0.0      0.0   
180     0.0      0.0      0.0      0.0      1.0     0.0     0.0      0.0   
161     0.0      0.0      0.0      0.0      0.0     0.0     0.0      0.0   
437     0.0      0.0      0.0      0.0      1.0     1.0     0.0      0.0   
320     0.0      0.0      0.0      0.0      1.0     0.0     0.0      0.0   

     PRE10_T  
id            
370      0.0  
236      1.0  
467      0.0  
216      1.0  
237      1.0  
..       ...  
4        0.0  
180      1.0  
161      0.0  
437      1.0  
320      0.0  

[118 rows x 15 columns]

In [142]:
X_test_encoded = pd.concat([X_test_num, X_test_cat_encoded], axis = 1)

In [143]:
X_test_encoded

PRE4   PRE5  AGE  PRE6_PRZ1  PRE6_PRZ2  PRE11_T  PRE14_OC12  PRE14_OC13  \
id                                                                             
370  3.80   3.16   59        0.0        0.0      0.0         1.0         0.0   
236  4.16   3.64   62        1.0        0.0      0.0         1.0         0.0   
467  3.76   3.12   61        0.0        0.0      0.0         0.0         0.0   
216  2.66   8.56   61        1.0        0.0      0.0         1.0         0.0   
237  3.20   1.80   74        1.0        0.0      1.0         1.0         0.0   
..    ...    ...  ...        ...        ...      ...         ...         ...   
4    3.68   3.04   54        0.0        0.0      0.0         0.0         0.0   
180  3.00   2.36   60        0.0        1.0      1.0         1.0         0.0   
161  2.92   1.88   76        0.0        0.0      0.0         1.0         0.0   
437  4.80   3.32   54        1.0        0.0      0.0         1.0         0.0   
320  2.10  69.10   62        0.0        0.0      0.0         0.0         0.0   

     PRE14_OC14  PRE8_T  PRE32_T  PRE19_T  PRE25_T  PRE30_T  PRE9_T  PRE7_T  \
id                                                                            
370         0.0     0.0      0.0      0.0      0.0      1.0     0.0     0.0   
236         0.0     0.0      0.0      0.0      0.0      1.0     0.0     0.0   
467         0.0     0.0      0.0      0.0      0.0      1.0     0.0     0.0   
216         0.0     1.0      0.0      0.0      0.0      1.0     0.0     0.0   
237         0.0     0.0      0.0      0.0      0.0      1.0     0.0     0.0   
..          ...     ...      ...      ...      ...      ...     ...     ...   
4           0.0     0.0      0.0      0.0      0.0      0.0     0.0     0.0   
180         0.0     0.0      0.0      0.0      0.0      1.0     0.0     0.0   
161         0.0     0.0      0.0      0.0      0.0      0.0     0.0     0.0   
437         0.0     0.0      0.0      0.0      0.0      1.0     1.0     0.0   
320         0.0     0.0      0.0      0.0      0.0      1.0     0.0     0.0   

     PRE17_T  PRE10_T  
id                     
370      0.0      0.0  
236      0.0      1.0  
467      0.0      0.0  
216      0.0      1.0  
237      0.0      1.0  
..       ...      ...  
4        0.0      0.0  
180      0.0      1.0  
161      0.0      0.0  
437      0.0      1.0  
320      0.0      0.0  

[118 rows x 18 columns]

In [146]:
# 표준화는 ... train데이터 쓴거로 ..
X_test_std = scaler.transform(X_test_encoded)

In [147]:
X_test_std

array([[ 0.60699024, -0.12318138, -0.39775954, ..., -0.27050089,
        -0.26440275, -1.47348945],
       [ 1.02314456, -0.08309524, -0.04058771, ..., -0.27050089,
        -0.26440275,  0.67866112],
       [ 0.56075087, -0.12652189, -0.15964498, ..., -0.27050089,
        -0.26440275, -1.47348945],
       ...,
       [-0.41027588, -0.23007777,  1.62621416, ..., -0.27050089,
        -0.26440275, -1.47348945],
       [ 1.76297446, -0.10981933, -0.99304592, ..., -0.27050089,
        -0.26440275,  0.67866112],
       [-1.35818294,  5.38365273, -0.04058771, ..., -0.27050089,
        -0.26440275, -1.47348945]])

# 로지스틱 회귀

In [148]:
from sklearn.linear_model import LogisticRegression

In [149]:
logistic = LogisticRegression(random_state=1)

In [152]:
logistic.fit(X_train_std, y_train)

LogisticRegression(random_state=1)

In [170]:
# logistic.predict(X_train_std, y_train)
logistic.score(X_train_std, y_train)

0.8465909090909091

In [171]:
logistic.score(X_test_std, y_test)

0.8305084745762712

## 테스트셋 정오분류표

In [172]:
from sklearn.metrics import confusion_matrix

In [173]:
y_pred = logistic.predict(X_test_std)

In [174]:
y_pred.shape

(118,)

In [184]:
y_pred[y_pred == y_test].shape[0] / y_test.shape[0]

0.8305084745762712

In [186]:
confusion_matrix(y_test, y_pred)

array([[98,  2],
       [18,  0]])

In [187]:
from sklearn.metrics import precision_score
precision_score(y_test, y_pred, average=None)

array([0.84482759, 0.        ])

In [188]:
from sklearn.metrics import recall_score
recall_score(y_test, y_pred)

0.0

In [215]:
new_data = pd.DataFrame([[3.36, 2.67, "PRZ1", 'F', 'F', 'F', 'F', 'F',
                         'OC11', 'F', 'F', 'F', 'T', 'F', 75]],
                        columns = ['PRE4', 'PRE5', 'PRE6', 'PRE7', 'PRE8'
                                   , 'PRE9', 'PRE10', 'PRE11', 'PRE14'
                                   , 'PRE17', 'PRE19', 'PRE25', 'PRE30', 'PRE32', 'AGE'] )

In [216]:
new_data

PRE4  PRE5  PRE6 PRE7 PRE8 PRE9 PRE10 PRE11 PRE14 PRE17 PRE19 PRE25 PRE30  \
0  3.36  2.67  PRZ1    F    F    F     F     F  OC11     F     F     F     T   

  PRE32  AGE  
0     F   75

In [217]:
new_data_cat = new_data[X_test_cat.columns]
new_data_num = new_data[X_test_num.columns]

In [218]:
new_data_cat

PRE6 PRE11 PRE14 PRE8 PRE32 PRE19 PRE25 PRE30 PRE9 PRE7 PRE17 PRE10
0  PRZ1     F  OC11    F     F     F     F     T    F    F     F     F

In [219]:
new_data_num

PRE4  PRE5  AGE
0  3.36  2.67   75

In [221]:
new_data_cat_encoded = pd.DataFrame(one_hot_encoder.transform(new_data_cat),
                                    columns = one_hot_encoder.get_feature_names_out(),
                                    index = new_data_cat.index)



In [222]:
new_data_encoded = pd.concat([new_data_num, new_data_cat_encoded], axis = 1)

In [223]:
new_data_encoded

PRE4  PRE5  AGE  PRE6_PRZ1  PRE6_PRZ2  PRE11_T  PRE14_OC12  PRE14_OC13  \
0  3.36  2.67   75        1.0        0.0      0.0         0.0         0.0   

   PRE14_OC14  PRE8_T  PRE32_T  PRE19_T  PRE25_T  PRE30_T  PRE9_T  PRE7_T  \
0         0.0     0.0      0.0      0.0      0.0      1.0     0.0     0.0   

   PRE17_T  PRE10_T  
0      0.0      0.0

In [225]:
# 표준화
new_data_std = scaler.transform(new_data_encoded)

In [227]:
logistic.predict(new_data_std) # 예측값이 0이므로 생존 예측...

array([0])

# 서포트 벡터 머신 분류기

In [228]:
from sklearn.svm import SVC

In [229]:
svc = SVC(kernel = 'rbf', random_state=1)

In [230]:
svc.fit(X_train_std, y_train)

SVC(random_state=1)

In [231]:
svc.score(X_train_std, y_train)

0.8778409090909091

In [232]:
svc.score(X_test_std, y_test)

0.847457627118644

In [234]:
confusion_matrix(y_test, svc.predict(X_test_std))

array([[100,   0],
       [ 18,   0]])

모두 0 으로 예측..

로지스틱 회귀랑 같은 비슷한 문제......

정확도는 83%로 높은편이지만... 정밀도와 재현률이 모두 0임...

따라서 분류모형으로서 효용성 앖ㅇ,ㅁ...

이는 분류하고자 하는 클래스의 비율이 불균형일때 흔히 발생하는 문제...

**정확성만 보고 모형을 평가하는것은 위험하다는것을 알 수 있다..**

깊이 제한이 없는 결정트리 분류기를 훈련시키고 (random_state = 1) 정확도를 구하시오. 또한 관측되는 현상을 설명하시오

In [236]:
from sklearn.tree import DecisionTreeClassifier

In [238]:
full_tree = DecisionTreeClassifier(random_state = 1)
full_tree.fit(X_train_std, y_train)

DecisionTreeClassifier(random_state=1)

In [240]:
full_tree.score(X_train_std, y_train)

1.0

In [241]:
full_tree.score(X_test_std, y_test)

0.7372881355932204

훈련데이터에 대한 점수는 높지만, 테스트데이터에 대한 점수는 낮음.. 과대적합 ㅎ현상ㅂ

깊이가 4인 결정트리 분류기를 훈련시키고 테스트셋에 대한 이트리 모형의 정오분류표를 구하시오

In [242]:
tree = DecisionTreeClassifier(random_state =1 , max_depth = 4)

In [243]:
tree.fit(X_train_std, y_train)

DecisionTreeClassifier(max_depth=4, random_state=1)

In [246]:
tree.score(X_train_std, y_train)

0.8835227272727273

In [245]:
tree.score(X_test_std, y_test)

0.8305084745762712

In [247]:
confusion_matrix(y_test, tree.predict(X_test_std))

array([[98,  2],
       [18,  0]])

로지스틱 회귀와 같은 문제 발생..